from fastapi import APIRouter
from app.api.v1.endpoints import (
    auth, users, transactions, team, ranks, bonuses, 
    admin, admin_users, admin_bonuses, admin_support, admin_analytics, admin_config, admin_books, admin_promo_materials, admin_activation, admin_bonus, admin_email, admin_videos,
    payments, payouts, notifications, events, promo_materials, books, activation, support, verification, crypto_signals, dashboard, videos, content, faq, blog, about, contact, social, upload, rbac, team_members
)

api_router = APIRouter()

api_router.include_router(auth.router, prefix="/auth", tags=["Authentication"])
api_router.include_router(users.router, prefix="/users", tags=["Users"])
api_router.include_router(transactions.router, prefix="/transactions", tags=["Transactions"])
api_router.include_router(team.router, prefix="/team", tags=["Team"])
api_router.include_router(ranks.router, prefix="/ranks", tags=["Ranks"])
api_router.include_router(bonuses.router, prefix="/bonuses", tags=["Bonuses"])
api_router.include_router(payments.router, prefix="/payments", tags=["Payments"])
api_router.include_router(payouts.router, prefix="/payouts", tags=["Payouts"])
api_router.include_router(notifications.router, prefix="/notifications", tags=["Notifications"])
api_router.include_router(events.router, prefix="/events", tags=["Events"])
api_router.include_router(promo_materials.router, prefix="/promo-materials", tags=["Promotional Materials"])
api_router.include_router(books.router, prefix="/books", tags=["Books"])
api_router.include_router(activation.router, prefix="/activation", tags=["Activation"])
api_router.include_router(support.router, prefix="/support", tags=["Support"])
api_router.include_router(verification.router, prefix="/verification", tags=["Verification"])
api_router.include_router(crypto_signals.router, prefix="/crypto", tags=["Crypto Signals"])
api_router.include_router(dashboard.router, prefix="/dashboard", tags=["Dashboard"])
api_router.include_router(videos.router, prefix="/videos", tags=["Videos"])
api_router.include_router(content.router, prefix="/content", tags=["Content"])
api_router.include_router(faq.router, prefix="/faq", tags=["FAQ"])
api_router.include_router(blog.router, prefix="/blog", tags=["Blog"])
api_router.include_router(about.router, prefix="/about", tags=["About"])
api_router.include_router(contact.router, prefix="/contact", tags=["Contact"])
api_router.include_router(social.router, prefix="/social", tags=["Social"])
api_router.include_router(upload.router, prefix="/upload", tags=["Upload"])
api_router.include_router(admin_videos.router, prefix="/admin/videos", tags=["Admin - Videos"])
api_router.include_router(admin_config.router, prefix="/admin/config", tags=["Admin - Configuration"])
api_router.include_router(admin_bonus.router, prefix="/admin/config", tags=["Admin - Bonus Configuration"])
api_router.include_router(admin_email.router, prefix="/admin/config", tags=["Admin - Email Configuration"])
api_router.include_router(admin_activation.router, prefix="/admin/activation-packages", tags=["Admin - Activation Packages"])
api_router.include_router(rbac.router, prefix="/admin/rbac", tags=["Admin - RBAC"])
api_router.include_router(admin.router, prefix="/admin", tags=["Admin - Finance"])
api_router.include_router(admin_users.router, prefix="/admin", tags=["Admin - Users"])
api_router.include_router(admin_bonuses.router, prefix="/admin", tags=["Admin - Bonuses"])
api_router.include_router(admin_support.router, prefix="/admin", tags=["Admin - Support"])
api_router.include_router(admin_analytics.router, prefix="/admin", tags=["Admin - Analytics"])
api_router.include_router(admin_books.router, prefix="/admin", tags=["Admin - Books"])
api_router.include_router(admin_promo_materials.router, prefix="/admin", tags=["Admin - Promo Materials"])
api_router.include_router(admin_activation.router, prefix="/admin", tags=["Admin - Activation Payments"])
api_router.include_router(team_members.router, prefix="/team-members", tags=["Team Members"])
